Repository Satyam1923/Spring-Music-Player, pull requests merged in 2024-06, with the labels that each got.

#248 Create Learn.md
  Learn.md
Labels: documentation, good first issue, gssoc, level1

#229 Feat: 404 not found page added with config #216
  frontend/package-lock.json
  frontend/src/App.jsx
  frontend/src/Images/404.png
  frontend/src/components/PagenotFound.css
  frontend/src/components/PagenotFound.jsx
Labels: enhancement, good first issue, gssoc, level2

#238 Implemented home page design
  frontend/src/App.jsx
  frontend/src/components/Home/Home.jsx
  frontend/src/components/Navbar.jsx
Labels: gssoc, level3

#232 Figma template UI 2nd version
  frontend/index.html
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/components/Genres.jsx
  frontend/src/components/Section3.jsx
  frontend/src/components/Sidebar.jsx
  frontend/src/components/TopArtists.jsx
  frontend/src/components/TopCharts.jsx
  frontend/src/components/TrackItem.jsx
  frontend/src/components/sidebar.css
Labels: enhancement, gssoc, level2

#259 increased music quality from 12kbps to 320kbps
  frontend/package-lock.json
  frontend/src/App.jsx
  frontend/src/components/Section3.jsx
Labels: gssoc

#260 Update README.md
  README.md
Labels: documentation, gssoc

#261 Removed all unnecessary CSS stylings from website #251
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/components/Sidebar.jsx
Labels: enhancement, gssoc, level2

#262 About Us and Contact Us pages were added
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/Aboutus.css
  frontend/src/pages/Aboutus.jsx
  frontend/src/pages/Contactus.css
  frontend/src/pages/Contactus.jsx
Labels: enhancement, gssoc, level2

#267 Fixed search bar text-align
  frontend/src/App.css
Labels: bug, gssoc, level1

#245 Added Dockerfile
  README.md
  backend/.dockerignore
  backend/Dockerfile
  frontend/.dockerignore
  frontend/Dockerfile
  frontend/vite.config.js
Labels: enhancement, gssoc, level2

#208 Made the footer
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/components/Footer.jsx
  frontend/tailwind.config.js
Labels: enhancement, gssoc, level1

#282 Fix issue 276 (multiple Readme files)
  LEARN.md
  Learn.md
Labels: documentation, gssoc

#283 Added the github icon
  frontend/src/components/Footer.jsx
Labels: enhancement, good first issue, gssoc

#228 re-designed-sidebar-#212
  frontend/src/App.css
  frontend/src/components/Sidebar.jsx
  frontend/src/components/sidebar.css
Labels: help wanted, gssoc, level2

#291 Updated the twitter icon
  frontend/src/components/Footer.jsx
Labels: bug, good first issue, gssoc

#299 Issue#294 fixed. Added Terms and Policy Page.
  frontend/src/App.jsx
  frontend/src/components/Footer.jsx
  frontend/src/pages/Terms.jsx
Labels: enhancement, gssoc, level1

#309 Issue#307 fixed. Added responsiveness for the contact page.
  frontend/src/pages/Contactus.jsx
Labels: enhancement, gssoc, level1

#225 Allow users to mark songs as favorites for quick access
  frontend/src/App.jsx
  frontend/src/components/Section3.jsx
  frontend/src/components/Sidebar.jsx
Labels: good first issue, gssoc, level2

#301 Implemented new search all page design
  frontend/src/App.jsx
  frontend/src/Utils.js
  frontend/src/components/Footer.jsx
  frontend/src/components/Home/Home.jsx
  frontend/src/components/MusicPlayer.jsx
  frontend/src/components/Navbar.jsx
  frontend/src/components/PagenotFound.jsx
  frontend/src/components/Search/Search.jsx
  frontend/src/components/Search/SearchBar.jsx
  frontend/src/pages/Terms.jsx
Labels: enhancement, gssoc, level3

#325 added preloader
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Images/preloader.json
  frontend/src/main.jsx
  frontend/src/pages/Preloader.css
  frontend/src/pages/Preloader.jsx
Labels: enhancement, gssoc, level1

#318 authentication done using email and password
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/components/Auth/Login.jsx
  frontend/src/components/Auth/SignUp.jsx
  frontend/src/components/Auth/firebase.js
  frontend/src/components/Home/Home.jsx
  frontend/src/components/UserIconSection.jsx
Labels: enhancement, help wanted, gssoc, level3

#361 about us page hover effect
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/aboutcard.jsx
  frontend/src/pages/Aboutus.jsx
Labels: enhancement, gssoc, level1

#337 Designing Login, Signup page and User Profile page in Figma #21
  README.md
Labels: enhancement, gssoc, level2

#385 done #364
  frontend/src/App.css
  frontend/src/components/Footer.jsx
Labels: enhancement, good first issue, gssoc, level1

#396 Adds Billboard top artist extraction with caching and error handling.
  backend/index.js
  backend/package-lock.json
  backend/package.json
  backend/routes/getTopArtists.js
  backend/routes/scheduler.js
Labels: enhancement, gssoc, level2

#387 Added artists manually and fetching their songs
  frontend/src/components/Footer.jsx
  frontend/src/components/Home/Home.jsx
Labels: enhancement, gssoc, level3

#414 Adding albums section in Search page
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/Utils.js
  frontend/src/components/Search/Search.jsx
  frontend/src/components/Search/SearchAlbums.jsx
Labels: enhancement, gssoc, level2

#297 Liked song page
  frontend/package-lock.json
  frontend/src/App.jsx
  frontend/src/components/LikedSong.jsx
  frontend/src/components/Navbar.jsx
  frontend/src/components/Sidebar.jsx
  frontend/src/components/likedsong.css
  frontend/vite.config.js
  vercel.json
Labels: enhancement, gssoc, level2

#423 add docker-compose file
  docker-compose.yml
Labels: gssoc, level1

#419 Search song
  frontend/.env.sample
  frontend/.gitignore
  frontend/src/components/Auth/Login.jsx
  frontend/src/components/Auth/StoreSong.js
  frontend/src/components/Auth/firebase.js
  frontend/src/components/Search/Search.jsx
  frontend/src/components/UserIconSection.jsx
  frontend/src/redux/auth-slice.js
Labels: enhancement, gssoc, level3

#427 Album page
  frontend/src/App.jsx
  frontend/src/Utils.js
  frontend/src/components/Album.jsx
  frontend/src/components/Home/Home.jsx
  frontend/src/components/Search/Search.jsx
  frontend/src/components/Search/SearchAlbums.jsx
Labels: enhancement, gssoc, level3

#447 Issue#446 fixed. Updated the about us page responsiveness.
  frontend/src/components/aboutcard.jsx
  frontend/tailwind.config.js
Labels: gssoc, level1
