Repository Satyam1923/Spring-Music-Player, pull requests merged in 2024-05, with the labels that each got.

#30 feat: added issue btns and respective forms
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: good first issue, GSSoC'24, level- 1

#40 feat: automated greetings by setting up CI
  .github/workflows/greetings.yml
Labels: documentation, gssoc, level1

#59 Making layout responsive
  frontend/src/App.css
Labels: bug, good first issue, gssoc, level1

#71 Added support for ENV varialbles
  backend/index.js
  frontend/.env.sample
  frontend/.gitignore
  frontend/src/App.jsx
Labels: good first issue, gssoc, level1

#172 Fixed Overlapping of paragraph #171
  frontend/src/App.css
  frontend/src/components/Section3.jsx
Labels: bug, good first issue, gssoc

#184 Added Background gradient from issue #119
  frontend/src/App.css
Labels: good first issue, gssoc, level2

#183 Update README.md
  README.md
Labels: documentation, good first issue, gssoc

#188 added workflow for closing old PRs
  .github/workflows/close-old-pr.yml
Labels: documentation, good first issue, gssoc, level1

#189 added workflow for closing old issues
  .github/workflows/close-old-issue.yml
Labels: documentation, enhancement, gssoc, level1

#196 feat: auth-redux
  backend/index.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/main.jsx
  frontend/src/redux/auth-slice.js
  frontend/src/redux/store.js
Labels: gssoc, level2

#210 issue #205
  backend/index.js
  backend/package-lock.json
  backend/package.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/components/Section3.jsx
  frontend/src/components/Sidebar.jsx
  frontend/src/components/sidebar.css
  frontend/src/main.jsx
  frontend/src/redux/store.js
Labels: enhancement, help wanted, gssoc, level2
