Repository Satyam1923/Spring-Music-Player, pull requests merged in 2024-07, with the labels that each got.

#460 Resolved Documentation for Spring Music Player
  README.md
Labels: good first issue, gssoc

#457 updated ui of searchbar
  frontend/src/components/Search/SearchBar.css
  frontend/src/components/Search/SearchBar.jsx
Labels: bug, gssoc, level1

#445 updated recently played tile ui
  frontend/src/components/Auth/Login.jsx
  frontend/src/components/Home/Home.jsx
Labels: enhancement, gssoc, level1, level3

#463 Added the contributors page
  frontend/src/App.jsx
  frontend/src/components/Footer.jsx
  frontend/src/pages/Contributors.jsx
Labels: enhancement, gssoc, level2

#473 Fixed songs and artist name alignment
  frontend/src/components/Home/Home.jsx
Labels: bug, gssoc, level1

#480 Resolving issue no.#366
  frontend/src/components/Footer.jsx
  frontend/src/components/Home/Home.jsx
  frontend/src/components/MusicPlayer.jsx
Labels: good first issue, gssoc, level1

#451 artist particualr pagw with their songs
  frontend/src/App.jsx
  frontend/src/Utils.js
  frontend/src/components/Artist.jsx
  frontend/src/components/Search/Search.jsx
Labels: enhancement, gssoc, level1, level2

#482 login page updated
  frontend/src/components/Auth/Login.jsx
  frontend/src/components/Auth/StoreSong.js
  frontend/src/components/Auth/firebase.js
  frontend/src/pages/Preloader.jsx
Labels: bug, gssoc, level1

#495 added the animation when like button is clicked
  frontend/src/App.css
  frontend/src/components/MusicPlayer.jsx
Labels: enhancement, gssoc, level1

#493 Fixed Search-All Top Results song play button working
  frontend/src/components/MusicPlayer.jsx
  frontend/src/components/Search/Search.jsx
Labels: bug, gssoc, level1

#501 Feat: Autoplay next song in search list
  frontend/src/components/MusicPlayer.jsx
  frontend/src/components/Search/Search.jsx
  package-lock.json
Labels: question, gssoc
